import mpgClasses

p = mpgClasses.RecurUpdate("test_python-1271187587.31")
p.setCustId ("cust 1")
p.setRecurAmount("1.00")
p.setPan("4242424242424242")
p.setExpDate("1111")
p.setAddNumRecurs("1")
p.setTotalNumRecurs("20")
##p.setHold("")
##p.setTerminate("")


req = mpgClasses.mpgHttpsPost("esqa.moneris.com", "moneris", "hurgle", p)
req.postRequest()
resp = req.getResponse()
print ("ReceiptId: " + resp.getReceiptId()) 
print ("ReferenceNum: " + resp.getReferenceNum()) 
print ("ResponseCode: " + resp.getResponseCode()) 
print ("ISO: " + resp.getISO()) 
print ("AuthCode: " + resp.getAuthCode()) 
print ("TransTime: " + resp.getTransTime()) 
print ("TransDate: " + resp.getTransDate()) 
print ("TransType: " + resp.getTransType()) 
print ("Complete: " + resp.getComplete()) 
print ("Message: " + resp.getMessage()) 
print ("TransAmount: " + resp.getTransAmount()) 
print ("CardType: " + resp.getCardType()) 
print ("TransID: " + resp.getTransID()) 
print ("TimedOut: " + resp.getTimedOut()) 
print ("RecurUpdateSuccess: " + resp.getRecurUpdateSuccess())
print ("NextRecurDate: " + resp.getNextRecurDate())
print ("RecurEndDate: " + resp.getRecurEndDate())

